// =============================================
//  Jo-ann Obewe – Portfolio Script
//  L04: JS basics | L05: localStorage | L06: fetch
// =============================================
 
console.log("Portfolio loaded – Jo-ann Obewe");
 
// --- State variable (L04) ---
let isDark = false;
 
// --- Restore saved theme from localStorage on page load (L05) ---
const savedTheme = localStorage.getItem("portfolio_theme");
if (savedTheme === "dark") {
    document.body.classList.add("dark");
    document.body.classList.remove("light");
    isDark = true;
    const btn = document.getElementById("themeToggle");
    if (btn) btn.textContent = "☀️";
    console.log("Theme restored: dark");
} else {
    console.log("Theme restored: light");
}
 
// --- setTheme function (L04) ---
function setTheme(dark) {
    if (dark) {
        document.body.classList.add("dark");
        document.body.classList.remove("light");
        localStorage.setItem("portfolio_theme", "dark");
        const btn = document.getElementById("themeToggle");
        if (btn) btn.textContent = "☀️";
        console.log("Theme changed: dark");
    } else {
        document.body.classList.remove("dark");
        document.body.classList.add("light");
        localStorage.setItem("portfolio_theme", "light");
        const btn = document.getElementById("themeToggle");
        if (btn) btn.textContent = "🌙";
        console.log("Theme changed: light");
    }
}
 
// --- Event listener: theme toggle button (L04) ---
const themeBtn = document.getElementById("themeToggle");
if (themeBtn) {
    themeBtn.addEventListener("click", function () {
        isDark = !isDark;
        setTheme(isDark);
    });
}
 
// --- Event listener: mobile burger menu (L04) ---
const burger   = document.getElementById("burger");
const navLinks = document.getElementById("navLinks");
if (burger && navLinks) {
    burger.addEventListener("click", function () {
        navLinks.classList.toggle("open");
        console.log("Mobile menu toggled");
    });
}
 
// --- showGreeting function (L04) ---
function showGreeting() {
    const hour = new Date().getHours();
    let greeting = "Welcome";
    if (hour < 12)      greeting = "Good morning";
    else if (hour < 18) greeting = "Good afternoon";
    else                greeting = "Good evening";
    console.log(greeting + " – thanks for visiting Jo-ann's portfolio!");
}
showGreeting();
 
// --- Last updated date generated by JavaScript (L05) ---
const lastUpdatedEl = document.getElementById("lastUpdated");
if (lastUpdatedEl) {
    const today   = new Date();
    const dateStr = today.toISOString().split("T")[0];
    lastUpdatedEl.textContent = "Last updated: " + dateStr;
}
 
// --- Active nav link on scroll ---
const pageSections = document.querySelectorAll(".page-section");
const navAnchors   = document.querySelectorAll("nav a[href^='#']");
 
window.addEventListener("scroll", function () {
    let current = "";
    pageSections.forEach(function (section) {
        if (window.scrollY >= section.offsetTop - 80) {
            current = section.getAttribute("id");
        }
    });
    navAnchors.forEach(function (link) {
        link.classList.remove("active");
        if (link.getAttribute("href") === "#" + current) {
            link.classList.add("active");
        }
    });
});
 
// =============================================
//  L06 – Fetch API / async / await
// =============================================
 
// Why do we use async/await?
// async/await makes asynchronous code look and behave like
// normal sequential code. Without it we would have to chain
// .then() callbacks which become hard to read and maintain.
 
// Why do we check response.ok?
// fetch() does NOT automatically throw an error for HTTP error
// codes like 404 or 500. Checking response.ok lets us catch
// those failures and handle them ourselves instead of using bad data.
 
// Why do we use try/catch?
// Network requests can fail for many reasons such as no internet
// connection or the server being down. try/catch lets us handle
// those errors gracefully and show the user a clear message
// instead of the page crashing silently.
 
const loadDataBtn = document.getElementById("loadDataBtn");
const dataBox     = document.getElementById("dataBox");
 
async function loadUserData() {
    dataBox.innerHTML = "<p>Loading…</p>";
    console.log("Fetching data from API…");
 
    try {
        const response = await fetch("https://jsonplaceholder.typicode.com/users/1");
 
        if (!response.ok) {
            throw new Error("HTTP error: " + response.status);
        }
 
        const user = await response.json();
        console.log("Data loaded:", user.name);
 
        dataBox.innerHTML =
            "<p><strong>Name:</strong> "    + user.name         + "</p>" +
            "<p><strong>Email:</strong> "   + user.email        + "</p>" +
            "<p><strong>Company:</strong> " + user.company.name + "</p>";
 
    } catch (error) {
        console.log("Error:", error.message);
        dataBox.innerHTML = "<p>Error loading data. Please try again.</p>";
    }
}
 
if (loadDataBtn) {
    loadDataBtn.addEventListener("click", function () {
        console.log("Load Data button clicked");
        loadUserData();
    });
}
 